-- PostgreSQL schema for uRede (Supabase)
-- Applies to public schema with TABLE_PREFIX=urede_

BEGIN;

CREATE TABLE IF NOT EXISTS urede_cooperativas (
  id_singular   TEXT PRIMARY KEY,
  uniodonto     TEXT,
  cnpj          TEXT,
  cro_operadora TEXT,
  data_fundacao TEXT,
  raz_social    TEXT,
  codigo_ans    TEXT,
  federacao     TEXT,
  software      TEXT,
  tipo          TEXT,
  op_pr         TEXT
);

CREATE TABLE IF NOT EXISTS urede_cidades (
  cd_municipio_7     TEXT PRIMARY KEY,
  cd_municipio       TEXT,
  regional_saude     TEXT,
  nm_cidade          TEXT,
  uf_municipio       TEXT,
  nm_regiao          TEXT,
  cidades_habitantes INTEGER,
  id_singular        TEXT REFERENCES urede_cooperativas(id_singular)
);

CREATE TABLE IF NOT EXISTS urede_operadores (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  nome        TEXT,
  id_singular TEXT,
  email       TEXT,
  telefone    TEXT,
  whatsapp    TEXT,
  cargo       TEXT,
  status      INTEGER DEFAULT 1,
  CONSTRAINT chk_urede_operadores_status CHECK (status IN (0, 1))
);

CREATE TABLE IF NOT EXISTS urede_pedidos (
  id                         TEXT PRIMARY KEY,
  titulo                     TEXT NOT NULL,
  criado_por                 BIGINT REFERENCES urede_operadores(id),
  cooperativa_solicitante_id TEXT REFERENCES urede_cooperativas(id_singular),
  cooperativa_responsavel_id TEXT REFERENCES urede_cooperativas(id_singular),
  cidade_id                  TEXT NOT NULL REFERENCES urede_cidades(cd_municipio_7),
  especialidades             TEXT NOT NULL DEFAULT '[]',
  quantidade                 INTEGER NOT NULL DEFAULT 1,
  observacoes                TEXT,
  prioridade                 TEXT NOT NULL DEFAULT 'media',
  nivel_atual                TEXT NOT NULL DEFAULT 'singular',
  status                     TEXT NOT NULL DEFAULT 'novo',
  data_criacao               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  data_ultima_alteracao      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  prazo_atual                TIMESTAMPTZ NOT NULL,
  data_conclusao             TIMESTAMPTZ,
  responsavel_atual_id       TEXT,
  responsavel_atual_nome     TEXT,
  criado_por_user            TEXT,
  motivo_categoria           TEXT,
  beneficiarios_quantidade   INTEGER,
  excluido                   BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_pedidos_cidade ON urede_pedidos(cidade_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_coop_resp ON urede_pedidos(cooperativa_responsavel_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_coop_solic ON urede_pedidos(cooperativa_solicitante_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_nivel ON urede_pedidos(nivel_atual);
CREATE INDEX IF NOT EXISTS idx_pedidos_prazo ON urede_pedidos(prazo_atual);
CREATE INDEX IF NOT EXISTS idx_pedidos_status ON urede_pedidos(status);

CREATE TABLE IF NOT EXISTS auth_users (
  email TEXT PRIMARY KEY,
  password_hash TEXT NOT NULL,
  nome TEXT,
  display_name TEXT,
  telefone TEXT,
  whatsapp TEXT,
  cargo TEXT,
  cooperativa_id TEXT,
  papel TEXT DEFAULT 'operador',
  requested_papel TEXT,
  ativo INTEGER DEFAULT 1,
  data_cadastro TIMESTAMPTZ DEFAULT NOW(),
  confirmation_token TEXT,
  confirmation_expires_at TIMESTAMPTZ,
  email_confirmed_at TIMESTAMPTZ,
  approval_status TEXT,
  approval_requested_at TIMESTAMPTZ,
  approved_by TEXT,
  approved_at TIMESTAMPTZ,
  auto_approve INTEGER DEFAULT 0,
  must_change_password INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_auth_users_coop_role_status
  ON auth_users(cooperativa_id, papel, approval_status);

CREATE TABLE IF NOT EXISTS user_approval_requests (
  id TEXT PRIMARY KEY,
  user_email TEXT NOT NULL,
  cooperativa_id TEXT,
  approver_cooperativa_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL,
  decided_at TIMESTAMPTZ,
  decided_by TEXT,
  decision_notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_user_approval_requests_status
  ON user_approval_requests(status);
CREATE INDEX IF NOT EXISTS idx_user_approval_requests_approver
  ON user_approval_requests(approver_cooperativa_id, status);

CREATE TABLE IF NOT EXISTS urede_cobertura_logs (
  id TEXT PRIMARY KEY,
  cidade_id TEXT NOT NULL,
  cooperativa_origem TEXT,
  cooperativa_destino TEXT,
  usuario_email TEXT,
  usuario_nome TEXT,
  usuario_papel TEXT,
  detalhes TEXT,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cobertura_logs_cidade ON urede_cobertura_logs(cidade_id);
CREATE INDEX IF NOT EXISTS idx_cobertura_logs_origem ON urede_cobertura_logs(cooperativa_origem);
CREATE INDEX IF NOT EXISTS idx_cobertura_logs_destino ON urede_cobertura_logs(cooperativa_destino);

CREATE TABLE IF NOT EXISTS urede_auditoria_logs (
  id TEXT PRIMARY KEY,
  pedido_id TEXT REFERENCES urede_pedidos(id),
  usuario_id TEXT,
  usuario_nome TEXT,
  usuario_display_nome TEXT,
  acao TEXT NOT NULL,
  detalhes TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auditoria_pedido ON urede_auditoria_logs(pedido_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario ON urede_auditoria_logs(usuario_id);

CREATE TABLE IF NOT EXISTS urede_alertas (
  id TEXT PRIMARY KEY,
  pedido_id TEXT NOT NULL,
  pedido_titulo TEXT,
  destinatario_email TEXT NOT NULL,
  destinatario_nome TEXT,
  destinatario_cooperativa_id TEXT,
  tipo TEXT NOT NULL,
  mensagem TEXT,
  detalhes TEXT,
  lido INTEGER NOT NULL DEFAULT 0,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  disparado_por_email TEXT,
  disparado_por_nome TEXT
);

CREATE INDEX IF NOT EXISTS idx_urede_alertas_destinatario ON urede_alertas(destinatario_email);
CREATE INDEX IF NOT EXISTS idx_urede_alertas_pedido ON urede_alertas(pedido_id);
CREATE INDEX IF NOT EXISTS idx_urede_alertas_lido ON urede_alertas(lido);

CREATE TABLE IF NOT EXISTS urede_cooperativa_settings (
  cooperativa_id TEXT PRIMARY KEY,
  auto_recusar INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS urede_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
